name: Build
# on push all branches and release
on:
  push:
    branches:
      - '*'
  release:
    types:
      - published

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install && npm install -g @quasar/cli

      - name: Build
        run: python3 Build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: VmManager-build
          path: ./backend

      - name: Upload to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: VmManager-build.zip
          tag: ${{ github.ref }}
          file_glob: true

