name: Build
on: push

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install && npm install -g @quasar/cli

      - name: Build
        run: python3 Build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: VmManager-build
          path: ./backend

